name: Build, Push, and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  
 
      - name: Build Docker image
        run: |
          docker login -u insaneprotestor -p kmgkmg@25
          docker build -t insaneprotestor/sample:$GITHUB_REF_NAME-$GITHUB_SHA .
          docker push insaneprotestor/sample:$GITHUB_REF_NAME-$GITHUB_SHA
      - name: Update manifest file
        run: |
          git clone https://github.com/kshitijwohlig/gitops.git
          cd gitops
          git checkout main
          git config user.name "kshitijwohlig"
          git config user.email "kshitij.gaikwad@wohlig.com"
          yq e '.spec.template.spec.containers[0].image = "insaneprotestor/sample:${{ env.GITHUB_BRANCH }}"' -i deployment.yaml
          git add .
          git commit -m "updating newer image"
          git push origin main
