name: Build, Push, and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  
 
      - name: Build Docker image
        run: |
          docker login -u kshitijg -p kmgkmg@25
          docker build -t kshitijg/sample:$GITHUB_REF_NAME-$GITHUB_SHA .
          docker push kshitijg/sample:$GITHUB_REF_NAME-$GITHUB_SHA
      - name: Update manifest file
        run: |
          git clone https://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@github.com/kshitijwohlig/gitops.git
          cd gitops
          git checkout main
          git config user.name "kshitijwohlig"
          git config user.email "kshitij.gaikwad@wohlig.com"
          yq e '.spec.template.spec.containers[0].image = "kshitijg/sample:${{ env.GITHUB_BRANCH }}"' -i deplyments.yaml
          git add .
          git commit -m "updating newer image"
          git push origin main
